version: '3'
services:
  login:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on: 
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_DB=wcc_users
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wcc_users
    ports:
      - "3306:3306"
